apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cpuloadtest
  namespace: {{ .Values.image.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: cpuloadtest
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: phpnew
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          requests:
            memory: 100Mi
            cpu: 500m
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cpuload-service
  namespace: {{ .Values.image.namespace }}
spec:
  selector:
    app: cpuloadtest
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpuloadtest-hpa
  namespace: {{ .Values.image.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: cpuloadtest
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
